spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/universys
    username: univeradm
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        validator:
          apply-to-ddl: true

app:
  security:
    jwt:
      secret: yattroman
      expirationMs: 18000