spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/universys
    username: univeradm
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true