spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/universys
    username: univeradm
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        validator:
          apply-to-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8

app:
  security:
    jwt:
      secret: yattroman
      expirationMs: 1800000000